## * ------ COMO SE IDENTIFICA EL PIPELINE:
name: Regression Testing Pipeline
run-name: ${{github.actor}}👨🏻‍🔬 triggered Regression

## * ------ CUANDO SE EJECUTA EL PIPELINE
on:
  schedule:
  ## Que se corra cada media 10 de la noche:
  - cron: '0 22 * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests'
        type: choice
        required: true
        default: 'QA'
        options:
        - 'QA'
        - 'UAT'
        - 'staging'
        - 'production'

## * -------------
jobs:
  RegressionTesting:
    ## * ------------- PROPIEDADES DEL JOB DEL PIPELINE
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      ## * ------------- 
      ## * ------------- PASOS EN ORDEN DE EJECUCIÓN 
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npm run install:browsers

    - name: Run Playwright tests
      run: |
        npm run test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
